### ISSUE TITLE
file name

### ISSUE THREAD

**Issue by M1Aston** [sealj553/download-notify#1]
Nice, useful little add-on.

One thing, though. Would it be possible to add the filename to the "download complete" pop-up?  Makes things a bit easier (at least for me:-)).

**Comment by sealj553** [comment]
Done, it should be updated in the add-ons page by now too.
Thanks for the feedback, I'm glad it's useful for you.

**Comment by M1Aston** [comment]
Thank you very much for your reply and the update. I really appreciate it.
